name-template: 'v$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
version-template: '$MAJOR.$MINOR.$PATCH'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
      - 'enhancement'
      - 'hotfix'
  default: 'minor'

categories:
  - title: 'ğŸš€ Enhancements'
    labels:
      - 'enhancement'
      - 'patch'
      - 'shell'
      - 'scripts'
      - 'terraform'
  - title: 'ğŸ› Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'hotfix'
  - title: 'ğŸ§° Included Tools'
    labels:
      - 'packages'
      - 'docker'
  - title: 'ğŸ“šï¸ Documentation'
    labels:
      - 'docs'
  - title: 'ğŸ—ï¸ Build/Release Maintenance'
    labels:
      - 'github'

autolabeler:
  - label: 'hotfix'
    branch:
      - '/release\/.+/'

change-template: |
  <details>
    <summary>$TITLE @$AUTHOR (#$NUMBER)</summary>
    $BODY
  </details>
template: |
  $CHANGES
replacers:
  # Remove irrelevant information from Renovate bot
  - search: '/(?<=---\s+)^#.*(Renovate configuration|Configuration)(?:.|\n)*?This PR has been generated .*/gm'
    replace: ''
  # Remove Renovate bot banner image
  - search: '/\[!\[[^\]]*Renovate\][^\]]*\](\([^)]*\))?\s*\n+/gm'
    replace: ''